### ISSUE TITLE
FTS zero touch fails at TASK [videoserver : Set service state] 

### ISSUE THREAD

**Issue by dtatum** [FreeTAKTeam/FreeTAKHub-Installation#56]
FTS zero touch fails at TASK [videoserver : Set service state] 

clean ubuntu 20.04/x86 install on ESXi 6.5.  script last grabbed at 1200PDT 2022.05.09.

install process...
```
wget -qO - bit.ly/ftszerotouch > fts.zero-touch.sh
chmod 760 fts.zero-touch.sh
sudo ./fts.zero-touch.sh
```
process fails with 
```
TASK [videoserver : Set service state] **************************************************************************************************
FAILED - RETRYING: [localhost]: Set service state (20 retries left).
<deleted repeat lines>
FAILED - RETRYING: [localhost]: Set service state (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 20, "changed": false, "msg": "Unable to start service rtsp-simple-server: "}
```
worked yesterday evening (2022.05.08) on same server (reverted with VMware snapshot).

**Comment by brothercorvo** [comment]
fixed in 1.9.9.5

**Comment by dtatum** [comment]
tested build b9fdbd1 in same environment, still getting the same problem of TASK [videoserver : Set service state] timing out.

**Comment by ultrablazed** [comment]
I am also still getting this issue using zerotouch on ubuntu server 20.04.4

**Comment by numpad0** [comment]
`$ cat /var/log/rtsp-simple-server/*`:
```
2022/09/01 07:56:20 INF rtsp-simple-server v0.20.0
2022/09/01 07:56:20 INF [RTSP] listener opened on :8554 (TCP)
2022/09/01 07:56:20 INF [RTMP] listener opened on :1935
2022/09/01 07:56:20 INF [HLS] listener opened on :8888
2022/09/01 07:56:20 ERR listen tcp 123.456.789.012:9997: bind: cannot assign requested address
2022/09/01 07:56:20 INF [RTSP] listener is closing
2022/09/01 07:56:20 INF [HLS] listener is closing
2022/09/01 07:56:20 INF [RTMP] listener is closing
2022/09/01 07:56:20 INF waiting for external commands
2022/09/01 07:56:27 INF rtsp-simple-server v0.20.0
```

`$ cat /opt/rtsp-simple-server.yml |grep 123.456.789.012`:
```
apiAddress: 123.456.789.012:9997
metricsAddress: 123.456.789.012:9998
```

I think I found the issue. The script is inserting global IPs in couple places, which don't work behind NAT. `0.0.0.0` should be used instead.
